// Copyright 2026 Aspect Build Systems, Inc. All rights reserved.

use core::convert::Infallible;
use core::future::Future;
use core::pin::Pin;
use core::sync::atomic::{AtomicU64, Ordering};
use core::task::{Context, Poll, ready};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use bytes::Bytes;
use futures_util::future::{BoxFuture, Either, ready};
use http::header::CONTENT_LENGTH;
use http::{HeaderMap, Request, Response, StatusCode};
use http_body::Body;

use crate::gate::{
    Admission, AdmissionState, AdmissionUnavailable, DecisionSource, PolicyGate, Subject,
};
use crate::metrics::{NoopPolicyGateMetrics, PolicyGateMetrics};
use crate::stream::EnforcedBody;
use crate::time::{TimeDriver, TokioTimeDriver};

/// Type-erased error accepted by the body adapter.
pub type BoxBodyError = Box<dyn core::error::Error + Send + Sync>;

const UNAVAILABLE_MESSAGE: &str = "Policy decision source is unavailable; retry the request.";
const MISSING_SUBJECT_LOG_INTERVAL_SECS: u64 = 60;
static NEXT_MISSING_SUBJECT_LOG: AtomicU64 = AtomicU64::new(0);

/// Rejection messages used by the Tower layer.
///
/// The message for an unavailable decision source is fixed, because it describes a retryable
/// server condition rather than a policy outcome; replace that response wholesale with
/// [`PolicyGateLayer::with_unavailable_response`].
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PolicyGateLayerConfig {
    denied_message: Arc<str>,
    missing_subject_message: Arc<str>,
}

impl PolicyGateLayerConfig {
    /// Creates the layer's rejection text.
    ///
    /// `denied_message` is returned for an authoritative denial, including the mid-stream cutoff
    /// of an already admitted request. `missing_subject_message` is returned when
    /// [`RequestPolicy::subject`] finds no subject on the request. Both messages reach clients, so
    /// keep them free of internal detail.
    #[must_use]
    pub fn new(
        denied_message: impl Into<Arc<str>>,
        missing_subject_message: impl Into<Arc<str>>,
    ) -> Self {
        Self {
            denied_message: denied_message.into(),
            missing_subject_message: missing_subject_message.into(),
        }
    }

    /// Returns the message rendered for an authoritative denial.
    #[must_use]
    pub fn denied_message(&self) -> &str {
        &self.denied_message
    }

    /// Returns the message rendered for a request that carries no subject.
    #[must_use]
    pub fn missing_subject_message(&self) -> &str {
        &self.missing_subject_message
    }
}

/// Host decisions needed by the context middleware.
///
/// One instance is shared by every request the layer handles, so the methods must be cheap,
/// side-effect free, and safe to call concurrently.
pub trait RequestPolicy<T: Subject>: Send + Sized + Sync + 'static {
    /// Returns the subject for this request.
    ///
    /// `None` rejects the request with the configured missing-subject response without consulting
    /// the gate. Resolve the subject from data already on the request, such as an extension
    /// inserted by an upstream authentication layer.
    fn subject<B>(&self, request: &Request<B>) -> Option<T>;

    /// Whether a mid-stream denial should reset the request body.
    ///
    /// Enable it for long-lived uploads and client-streaming RPCs, where a denial must interrupt
    /// data the client is still sending. Wrapping a body costs a policy check per frame.
    fn enforce_request_body<B>(&self, request: &Request<B>) -> bool;

    /// Whether a mid-stream denial should terminate the response body.
    ///
    /// Defaults to `true`. Enforcing the response body drops the `content-length` header, since a
    /// denial can truncate the body mid-flight; return `false` for responses that must keep an
    /// exact length.
    fn enforce_response_body<B>(&self, _request: &Request<B>) -> bool {
        true
    }
}

/// Converts arbitrary HTTP bodies into the single body type exposed by the layer.
///
/// The layer wraps request and response bodies to enforce mid-stream denials, which needs one
/// concrete body type for the whole stack. Implement this over the host framework's erased body —
/// the `axum-body` feature provides `AxumBodyAdapter` for Axum — and keep the adapter a
/// zero-sized handle.
pub trait BodyAdapter: Copy + Send + Sync + 'static {
    /// Body type accepted and returned by the wrapped service.
    type Body: Body<Data = Bytes, Error: Into<BoxBodyError>> + Send + 'static;

    /// Erases or otherwise adapts an arbitrary compatible body.
    fn adapt<B>(self, body: B) -> Self::Body
    where
        B: Body<Data = Bytes> + Send + 'static,
        B::Error: Into<BoxBodyError>;

    /// Creates a body containing response bytes generated by context.
    fn make_body(self, bytes: Bytes) -> Self::Body;
}

/// Axum's type-erased body adapter.
///
/// Requires the `axum-body` feature.
#[cfg(feature = "axum-body")]
#[derive(Clone, Copy, Debug, Default)]
pub struct AxumBodyAdapter;

#[cfg(feature = "axum-body")]
impl BodyAdapter for AxumBodyAdapter {
    type Body = axum_core::body::Body;

    fn adapt<B>(self, body: B) -> Self::Body
    where
        B: Body<Data = Bytes> + Send + 'static,
        B::Error: Into<BoxBodyError>,
    {
        axum_core::body::Body::new(body)
    }

    fn make_body(self, bytes: Bytes) -> Self::Body {
        axum_core::body::Body::from(bytes)
    }
}

/// Identifies which half of a streaming HTTP body was denied.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BodySide {
    /// The request body sent to the inner service.
    Request,
    /// The response body returned by the inner service.
    Response,
}

/// How a denied active stream should be terminated.
#[derive(Debug)]
pub enum StreamRejection {
    /// Fail the body with a transport-specific error.
    Error(Box<dyn core::error::Error + Send + Sync>),
    /// End the body with transport-specific trailers.
    Trailers(HeaderMap),
}

/// Terminates streams using the host transport's error or trailer representation.
pub trait StreamRejectionResponse: Copy + Send + Sync + 'static {
    /// Terminates an active stream denied after admission.
    ///
    /// Called at most once per body, in place of the next frame, after response headers may
    /// already have been sent. Trailers are the graceful choice where the transport carries status
    /// in them, such as gRPC responses; an error aborts the stream.
    fn stream_denied(self, side: BodySide, message: &str) -> StreamRejection;
}

/// Converts admission outcomes into responses appropriate for the host transport.
///
/// The `message` argument of each method is the corresponding text from
/// [`PolicyGateLayerConfig`]; implementations choose the status and encoding around it.
pub trait RejectionResponse<A: BodyAdapter>: StreamRejectionResponse {
    /// Renders an admission denied by the authority.
    fn denied(self, body: A, message: &str) -> Response<A::Body>;
    /// Renders a request for which the policy found no subject.
    fn missing_subject(self, body: A, message: &str) -> Response<A::Body>;
    /// Renders an admission for which no authoritative verdict was available.
    fn unavailable(self, body: A, error: AdmissionUnavailable, message: &str) -> Response<A::Body>;
}

/// Standard HTTP rendering for Tower/Hyper consumers.
///
/// Renders a plain-text body with the status the outcome maps to:
///
/// | Outcome | Status |
/// | --- | --- |
/// | denied | `429 Too Many Requests` |
/// | missing subject | `400 Bad Request` |
/// | unavailable | `503 Service Unavailable` |
///
/// A stream denied after admission fails with an error carrying the denial message, since plain
/// HTTP has no trailer status.
#[derive(Clone, Copy, Debug, Default)]
pub struct HttpRejectionResponse;

impl<A: BodyAdapter> RejectionResponse<A> for HttpRejectionResponse {
    fn denied(self, body: A, message: &str) -> Response<A::Body> {
        http_response(body, StatusCode::TOO_MANY_REQUESTS, message)
    }

    fn missing_subject(self, body: A, message: &str) -> Response<A::Body> {
        http_response(body, StatusCode::BAD_REQUEST, message)
    }

    fn unavailable(
        self,
        body: A,
        _error: AdmissionUnavailable,
        message: &str,
    ) -> Response<A::Body> {
        http_response(body, StatusCode::SERVICE_UNAVAILABLE, message)
    }
}

impl StreamRejectionResponse for HttpRejectionResponse {
    fn stream_denied(self, _side: BodySide, message: &str) -> StreamRejection {
        StreamRejection::Error(Box::new(LimitExceededError(message.to_owned())))
    }
}

/// Response policy that replaces only unavailable-admission rendering.
///
/// Produced by [`PolicyGateLayer::with_unavailable_response`]; denial, missing-subject, and
/// stream rejections keep the behavior of the wrapped policy `R`.
#[derive(Clone, Copy, Debug)]
pub struct UnavailableResponseAdapter<R, U> {
    inner: R,
    unavailable: U,
}

#[derive(Clone, Copy)]
struct ResponseContext<A, R> {
    body: A,
    response: R,
}

impl<A, R, U> RejectionResponse<A> for UnavailableResponseAdapter<R, U>
where
    A: BodyAdapter,
    R: RejectionResponse<A>,
    U: Copy + Fn(AdmissionUnavailable) -> Response<A::Body> + Send + Sync + 'static,
{
    fn denied(self, body: A, message: &str) -> Response<A::Body> {
        self.inner.denied(body, message)
    }

    fn missing_subject(self, body: A, message: &str) -> Response<A::Body> {
        self.inner.missing_subject(body, message)
    }

    fn unavailable(
        self,
        _body: A,
        error: AdmissionUnavailable,
        _message: &str,
    ) -> Response<A::Body> {
        (self.unavailable)(error)
    }
}

impl<R, U> StreamRejectionResponse for UnavailableResponseAdapter<R, U>
where
    R: StreamRejectionResponse,
    U: Copy + Send + Sync + 'static,
{
    fn stream_denied(self, side: BodySide, message: &str) -> StreamRejection {
        self.inner.stream_denied(side, message)
    }
}

#[derive(Debug)]
struct LimitExceededError(String);

impl core::fmt::Display for LimitExceededError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(&self.0)
    }
}

impl core::error::Error for LimitExceededError {}

/// Shared gate, rejection text, and metrics retained by request/response wrappers.
pub(crate) struct GateContext<T: Subject, C: DecisionSource<T>, M: PolicyGateMetrics, D> {
    pub(crate) gate: PolicyGate<T, C, M, D>,
    pub(crate) rejection_message: Arc<str>,
    missing_subject_message: Arc<str>,
    pub(crate) metrics: M,
}

impl<T: Subject, C: DecisionSource<T>, M: PolicyGateMetrics, D: TimeDriver> core::fmt::Debug
    for GateContext<T, C, M, D>
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("GateContext")
            .field("gate", &self.gate)
            .field("rejection_message", &self.rejection_message)
            .field("missing_subject_message", &self.missing_subject_message)
            .finish_non_exhaustive()
    }
}

/// Tower layer that rejects requests whose subject is denied or cannot be verified.
///
/// The layer resolves a subject through `P`, admits it through the gate, and — where `P` asks for
/// it — wraps the request and response bodies so a denial that lands mid-stream terminates the
/// transfer. Rejections are rendered by `R` and never reach the inner service.
///
/// Cloning is cheap; each clone shares the gate, policy, and rejection text.
///
/// Requires the `tower-layer` feature.
pub struct PolicyGateLayer<
    P,
    T,
    C,
    A,
    M = NoopPolicyGateMetrics,
    R = HttpRejectionResponse,
    D = TokioTimeDriver,
> where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
{
    context: Arc<GateContext<T, C, M, D>>,
    policy: Arc<P>,
    body: A,
    response: R,
}

impl<P, T, C, A, M, R, D> Clone for PolicyGateLayer<P, T, C, A, M, R, D>
where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
{
    fn clone(&self) -> Self {
        Self {
            context: Arc::clone(&self.context),
            policy: Arc::clone(&self.policy),
            body: self.body,
            response: self.response,
        }
    }
}

impl<P, T, C, A, M, R, D> core::fmt::Debug for PolicyGateLayer<P, T, C, A, M, R, D>
where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("PolicyGateLayer").finish_non_exhaustive()
    }
}

impl<P, T, C, A, M, D> PolicyGateLayer<P, T, C, A, M, HttpRejectionResponse, D>
where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    D: TimeDriver,
{
    /// Constructs a layer over the transport-neutral gate with plain HTTP rejection rendering.
    ///
    /// The layer observes the gate; it neither owns nor polls the gate's watcher, which the caller
    /// must keep polled as described in the [runtime contract](crate#runtime-contract).
    #[must_use]
    pub fn new(
        gate: PolicyGate<T, C, M, D>,
        config: &PolicyGateLayerConfig,
        policy: P,
        body: A,
    ) -> Self {
        Self::new_with_response(gate, config, policy, body, HttpRejectionResponse)
    }
}

impl<P, T, C, A, M, R, D> PolicyGateLayer<P, T, C, A, M, R, D>
where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D: TimeDriver,
{
    /// Constructs a layer with caller-defined response rendering.
    ///
    /// Use it to render rejections for a non-plain-HTTP transport, such as
    /// `TonicRejectionResponse` from the `tonic-layer` feature.
    #[must_use]
    pub fn new_with_response(
        gate: PolicyGate<T, C, M, D>,
        config: &PolicyGateLayerConfig,
        policy: P,
        body: A,
        response: R,
    ) -> Self {
        let metrics = gate.metrics();
        Self {
            context: Arc::new(GateContext {
                gate,
                rejection_message: Arc::clone(&config.denied_message),
                missing_subject_message: Arc::clone(&config.missing_subject_message),
                metrics,
            }),
            policy: Arc::new(policy),
            body,
            response,
        }
    }

    /// Replaces the response callback while retaining the configured gate and policy.
    ///
    /// Only the unavailable-admission response changes; denial, missing-subject, and stream
    /// rejections keep their current rendering. The callback runs on the request path, so it must
    /// not block.
    #[must_use]
    pub fn with_unavailable_response<F>(
        self,
        unavailable_response: F,
    ) -> PolicyGateLayer<P, T, C, A, M, UnavailableResponseAdapter<R, F>, D>
    where
        F: Copy + Fn(AdmissionUnavailable) -> Response<A::Body> + Send + Sync + 'static,
    {
        PolicyGateLayer {
            context: self.context,
            policy: self.policy,
            body: self.body,
            response: UnavailableResponseAdapter {
                inner: self.response,
                unavailable: unavailable_response,
            },
        }
    }
}

impl<S, P, T, C, A, M, R, D> tower::Layer<S> for PolicyGateLayer<P, T, C, A, M, R, D>
where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D: TimeDriver,
{
    type Service = PolicyGateMiddleware<S, P, T, C, A, M, R, D>;

    fn layer(&self, inner: S) -> Self::Service {
        PolicyGateMiddleware {
            inner,
            context: Arc::clone(&self.context),
            policy: Arc::clone(&self.policy),
            body: self.body,
            response: self.response,
        }
    }
}

/// Middleware produced by [`PolicyGateLayer`].
///
/// Its [`tower::Service`] implementation requires an inner service with `Error = Infallible`,
/// because every policy outcome is an ordinary HTTP response. Cached decisions are checked before
/// the middleware waits for an authority lookup.
///
/// Requires the `tower-layer` feature.
pub struct PolicyGateMiddleware<
    S,
    P,
    T,
    C,
    A,
    M = NoopPolicyGateMetrics,
    R = HttpRejectionResponse,
    D = TokioTimeDriver,
> where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
{
    inner: S,
    context: Arc<GateContext<T, C, M, D>>,
    policy: Arc<P>,
    body: A,
    response: R,
}

impl<S, P, T, C, A, M, R, D> Clone for PolicyGateMiddleware<S, P, T, C, A, M, R, D>
where
    S: Clone,
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D: TimeDriver,
{
    fn clone(&self) -> Self {
        Self {
            inner: self.inner.clone(),
            context: Arc::clone(&self.context),
            policy: Arc::clone(&self.policy),
            body: self.body,
            response: self.response,
        }
    }
}

impl<S, P, T, C, A, M, R, D> core::fmt::Debug for PolicyGateMiddleware<S, P, T, C, A, M, R, D>
where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D: TimeDriver,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("PolicyGateMiddleware")
            .field("rejection_message", &self.context.rejection_message)
            .finish_non_exhaustive()
    }
}

type LimitFuture<F, T, C, A, M, R, D> = Either<
    EnforcedResponseFuture<F, T, C, A, M, R, D>,
    BoxFuture<'static, Result<Response<<A as BodyAdapter>::Body>, Infallible>>,
>;

impl<S, ResBody, P, T, C, A, M, R, D> tower::Service<Request<A::Body>>
    for PolicyGateMiddleware<S, P, T, C, A, M, R, D>
where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T> + 'static,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D: TimeDriver,
    S: tower::Service<Request<A::Body>, Response = Response<ResBody>, Error = Infallible>
        + Clone
        + Send
        + 'static,
    S::Future: Send + 'static,
    ResBody: Body<Data = Bytes> + Send + 'static,
    ResBody::Error: Into<Box<dyn core::error::Error + Send + Sync>>,
{
    type Response = Response<A::Body>;
    type Error = Infallible;
    type Future = LimitFuture<S::Future, T, C, A, M, R, D>;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        self.inner.poll_ready(cx)
    }

    fn call(&mut self, request: Request<A::Body>) -> Self::Future {
        let Some(subject) = self.policy.subject(&request) else {
            self.context.metrics.missing_subject_rejection();
            if should_log_missing_subject() {
                tracing::warn!("verified request carries no subject id");
            }
            return Either::Right(Box::pin(ready(Ok(self
                .response
                .missing_subject(self.body, &self.context.missing_subject_message)))));
        };

        let refresh_disabled = self.context.gate.refresh_disabled();
        if refresh_disabled {
            if let Some(admission) = self.context.gate.try_cached_now(&subject) {
                if admission.is_allowed() {
                    return Either::Left(pass_through(
                        &mut self.inner,
                        request,
                        subject,
                        admission,
                        Arc::clone(&self.context),
                        self.policy.as_ref(),
                        ResponseContext {
                            body: self.body,
                            response: self.response,
                        },
                    ));
                }
                if admission.state() == AdmissionState::Denied {
                    return Either::Right(Box::pin(ready(Ok(deny(
                        &self.context,
                        self.body,
                        self.response,
                    )))));
                }
            }
            self.context.metrics.snapshot_miss();
        }

        // We must take the current `inner` and not the clone.
        // See: https://docs.rs/tower/latest/tower/trait.Service.html#be-careful-when-cloning-inner-services
        let clone = self.inner.clone();
        let mut inner = core::mem::replace(&mut self.inner, clone);
        let context = Arc::clone(&self.context);
        let policy = Arc::clone(&self.policy);
        let body = self.body;
        let response = self.response;
        Either::Right(Box::pin(async move {
            loop {
                match context.gate.admit(&subject).await {
                    Ok(admission) if admission.is_allowed() => {
                        return pass_through(
                            &mut inner,
                            request,
                            subject,
                            admission,
                            Arc::clone(&context),
                            policy.as_ref(),
                            ResponseContext { body, response },
                        )
                        .await;
                    }
                    Ok(admission) if admission.state() == AdmissionState::Denied => {
                        return Ok(deny(&context, body, response));
                    }
                    // A concurrent invalidation requires recovery, not a policy rejection.
                    Ok(_) => {}
                    Err(error) => {
                        context.metrics.unavailable_rejection();
                        return Ok(response.unavailable(body, error, UNAVAILABLE_MESSAGE));
                    }
                }
            }
        }))
    }
}

/// Unboxed snapshot-hit future that wraps the response stream.
#[pin_project::pin_project]
pub struct EnforcedResponseFuture<
    F,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D,
> {
    #[pin]
    inner: F,
    subject: T,
    admission: Option<Admission<D>>,
    context: Arc<GateContext<T, C, M, D>>,
    body: A,
    response: R,
    enforce_response_body: bool,
}

impl<
    F,
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D: TimeDriver,
> core::fmt::Debug for EnforcedResponseFuture<F, T, C, A, M, R, D>
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("EnforcedResponseFuture")
            .finish_non_exhaustive()
    }
}

impl<F, ResBody, T, C, A, M, R, D> Future for EnforcedResponseFuture<F, T, C, A, M, R, D>
where
    T: Subject,
    C: DecisionSource<T> + 'static,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D: TimeDriver,
    F: Future<Output = Result<Response<ResBody>, Infallible>>,
    ResBody: Body<Data = Bytes> + Send + 'static,
    ResBody::Error: Into<Box<dyn core::error::Error + Send + Sync>>,
{
    type Output = Result<Response<A::Body>, Infallible>;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let this = self.project();
        let response = ready!(this.inner.poll(cx))?;
        let admission = this
            .admission
            .take()
            .expect("response future completes once");
        let response = if *this.enforce_response_body {
            let (mut parts, body) = response.into_parts();
            // GateContext may truncate the body, so an original exact length is no longer valid.
            parts.headers.remove(CONTENT_LENGTH);
            Response::from_parts(
                parts,
                this.body.adapt(EnforcedBody::new(
                    body,
                    (*this.subject).clone(),
                    admission,
                    Arc::clone(this.context),
                    *this.response,
                    BodySide::Response,
                )),
            )
        } else {
            response.map(|body| this.body.adapt(body))
        };
        Poll::Ready(Ok(response))
    }
}

fn pass_through<S, ResBody, P, T, C, A, M, R, D>(
    inner: &mut S,
    request: Request<A::Body>,
    subject: T,
    admission: Admission<D>,
    context: Arc<GateContext<T, C, M, D>>,
    policy: &P,
    response_context: ResponseContext<A, R>,
) -> EnforcedResponseFuture<S::Future, T, C, A, M, R, D>
where
    P: RequestPolicy<T>,
    T: Subject,
    C: DecisionSource<T> + 'static,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D: TimeDriver,
    S: tower::Service<Request<A::Body>, Response = Response<ResBody>>,
{
    let ResponseContext {
        body: body_adapter,
        response,
    } = response_context;
    let enforce_request_body = policy.enforce_request_body(&request);
    let enforce_response_body = policy.enforce_response_body(&request);
    let request = if enforce_request_body {
        request.map(|body| {
            body_adapter.adapt(EnforcedBody::new(
                body,
                subject.clone(),
                admission.clone(),
                Arc::clone(&context),
                response,
                BodySide::Request,
            ))
        })
    } else {
        request
    };
    EnforcedResponseFuture {
        inner: inner.call(request),
        subject,
        admission: Some(admission),
        context,
        body: body_adapter,
        response,
        enforce_response_body,
    }
}

fn should_log_missing_subject() -> bool {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let next = NEXT_MISSING_SUBJECT_LOG.load(Ordering::Relaxed);
    now >= next
        && NEXT_MISSING_SUBJECT_LOG
            .compare_exchange(
                next,
                now.saturating_add(MISSING_SUBJECT_LOG_INTERVAL_SECS),
                Ordering::Relaxed,
                Ordering::Relaxed,
            )
            .is_ok()
}

fn deny<
    T: Subject,
    C: DecisionSource<T>,
    A: BodyAdapter,
    M: PolicyGateMetrics,
    R: RejectionResponse<A>,
    D: TimeDriver,
>(
    context: &GateContext<T, C, M, D>,
    body: A,
    response: R,
) -> Response<A::Body> {
    context.metrics.denial();
    response.denied(body, &context.rejection_message)
}

fn http_response<A: BodyAdapter>(body: A, status: StatusCode, message: &str) -> Response<A::Body> {
    let mut response = Response::new(body.make_body(Bytes::copy_from_slice(message.as_bytes())));
    *response.status_mut() = status;
    response
}
