// Copyright 2026 Aspect Build Systems, Inc. All rights reserved.

// This file is @generated by prost-build.
/// Looks one subject up in one scope.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSubjectDecisionRequest {
    /// Subject the decision is asked about.
    ///
    /// Required. The identifier is opaque to the wire: the client sends the exact string it
    /// gates on, and the authority MUST match it byte for byte rather than normalizing it.
    #[prost(string, tag = "1")]
    pub subject_id: ::prost::alloc::string::String,
    /// Scope the lookup applies to.
    ///
    /// Required. It is the scope the client is bound to, and is the same on every request
    /// that client sends.
    #[prost(string, tag = "2")]
    pub scope: ::prost::alloc::string::String,
}
/// The requested subject's decision.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSubjectDecisionResponse {
    /// Decision in force for the requested subject.
    #[prost(enumeration = "Decision", tag = "1")]
    pub decision: i32,
    /// Scope the decision was evaluated in.
    ///
    /// The authority MUST echo the request's scope. A client rejects a non-empty mismatch
    /// as a protocol failure, which keeps a misrouted or misconfigured authority from
    /// supplying verdicts for another scope. An empty echo is rejected the same way unless
    /// the client is configured to tolerate it while an authority that does not yet echo
    /// rolls out.
    #[prost(string, tag = "2")]
    pub scope: ::prost::alloc::string::String,
}
/// Opens one scope's change stream.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchSubjectDecisionsRequest {
    /// Scope to watch.
    ///
    /// Required. One stream carries one scope; a client that gates several scopes opens a
    /// stream per scope.
    #[prost(string, tag = "1")]
    pub scope: ::prost::alloc::string::String,
}
/// One subject's decision change within the watched scope.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubjectDecisionChange {
    /// Subject the change applies to.
    ///
    /// Required, and carried in the same form as GetSubjectDecisionRequest.subject_id. A
    /// client ignores a change for a subject it is not currently tracking, so the authority
    /// MAY send changes for the whole scope.
    #[prost(string, tag = "1")]
    pub subject_id: ::prost::alloc::string::String,
    /// Decision now in force for the subject.
    ///
    /// DECISION_UNSPECIFIED means the subject no longer has an authoritative decision.
    #[prost(enumeration = "Decision", tag = "2")]
    pub decision: i32,
    /// Scope the change was evaluated in.
    ///
    /// The authority MUST echo the watch request's scope, under the same rules as
    /// GetSubjectDecisionResponse.scope. A client that rejects a change ends the stream and
    /// reconnects.
    #[prost(string, tag = "3")]
    pub scope: ::prost::alloc::string::String,
}
/// Whether a subject may work within a scope.
///
/// A client rejects a value it does not know as a protocol failure, so adding a value
/// breaks deployed clients.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Decision {
    /// The authority holds no decision for the subject.
    ///
    /// As a lookup result it is not authoritative and the client retries until its
    /// admission deadline. As a change it withdraws the subject's cached decision and
    /// invalidates work already admitted under it.
    Unspecified = 0,
    /// The subject may start new work and continue work already admitted.
    Allowed = 1,
    /// The subject may not start new work, and work already admitted MUST stop.
    Denied = 2,
}
impl Decision {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DECISION_UNSPECIFIED",
            Self::Allowed => "DECISION_ALLOWED",
            Self::Denied => "DECISION_DENIED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DECISION_UNSPECIFIED" => Some(Self::Unspecified),
            "DECISION_ALLOWED" => Some(Self::Allowed),
            "DECISION_DENIED" => Some(Self::Denied),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod policy_authority_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    /// Serves the decision in force for each subject in a scope, and the later changes to it.
    ///
    /// Clients pair the two RPCs. The unary lookup answers whether one subject may start
    /// work; the watch stream keeps work already admitted current. Both are read-only, so
    /// retrying either is safe.
    #[derive(Debug, Clone)]
    pub struct PolicyAuthorityClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> PolicyAuthorityClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PolicyAuthorityClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                    http::Request<tonic::body::Body>,
                    Response = http::Response<
                        <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                    >,
                >,
            <T as tonic::codegen::Service<http::Request<tonic::body::Body>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PolicyAuthorityClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Returns the decision in force for one subject.
        ///
        /// The authority MUST answer a subject it holds no decision for with
        /// DECISION_UNSPECIFIED rather than NOT_FOUND.
        ///
        /// Clients treat NOT_FOUND, INVALID_ARGUMENT, PERMISSION_DENIED, UNAUTHENTICATED,
        /// UNIMPLEMENTED, and DATA_LOSS as permanent and fail the admission; every other status
        /// is transient and retried under the client's own deadline.
        pub async fn get_subject_decision(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSubjectDecisionRequest>,
        ) -> std::result::Result<tonic::Response<super::GetSubjectDecisionResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/aspect.policy.gate.v1.PolicyAuthority/GetSubjectDecision",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "aspect.policy.gate.v1.PolicyAuthority",
                "GetSubjectDecision",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Streams decision changes for every subject in one scope.
        ///
        /// The stream carries changes only. The authority is not required to open it with a
        /// snapshot, because a client looks a subject up with GetSubjectDecision before
        /// admitting it.
        ///
        /// The authority MAY end the stream at any time; ending it is not an error. A client
        /// discards its cached decisions on disconnect, reconnects with jittered backoff, and
        /// fails a new admission closed once its admission deadline passes with the stream
        /// still down. An authority that cannot keep up with a client SHOULD therefore end its
        /// stream rather than delay or drop individual changes.
        pub async fn watch_subject_decisions(
            &mut self,
            request: impl tonic::IntoRequest<super::WatchSubjectDecisionsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::SubjectDecisionChange>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/aspect.policy.gate.v1.PolicyAuthority/WatchSubjectDecisions",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "aspect.policy.gate.v1.PolicyAuthority",
                "WatchSubjectDecisions",
            ));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
